// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {apppost} from '../models';

export function AppPost(arg1:apppost.AppPostParam,arg2:string):Promise<apppost.AppPostResponse>;

export function MkCurl(arg1:apppost.AppPostParam,arg2:string):Promise<string>;

export function ParseCurl(arg1:string,arg2:string):Promise<apppost.AppPostParam>;
