// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppPost(arg1, arg2) {
  return window['go']['apppost']['AppPost']['AppPost'](arg1, arg2);
}

export function MkCurl(arg1, arg2) {
  return window['go']['apppost']['AppPost']['MkCurl'](arg1, arg2);
}

export function ParseCurl(arg1, arg2) {
  return window['go']['apppost']['AppPost']['ParseCurl'](arg1, arg2);
}
