// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadConf() {
  return window['go']['supervisor']['Service']['LoadConf']();
}

export function Projects(arg1) {
  return window['go']['supervisor']['Service']['Projects'](arg1);
}

export function RunCmd(arg1, arg2, arg3) {
  return window['go']['supervisor']['Service']['RunCmd'](arg1, arg2, arg3);
}
