// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {supervisor} from '../models';

export function LoadConf():Promise<Array<string>>;

export function Projects(arg1:string):Promise<Array<supervisor.CtlConf>|Error>;

export function RunCmd(arg1:string,arg2:Array<string>,arg3:string):Promise<Array<string>|Error>;
